### ISSUE TITLE
Group simmr output boxplot are always the same

### ISSUE THREAD

**Issue by JeromeL9** [andrewcparnell/simmr#23]
I am trying to produce output boxplots for groups of consumers but no matter which group I specify, it is always the same boxplot that is produced.

#Reading data
simmr_groups <- readRDS(file="mydata.rds")

plot(simmr_groups,group=1:4,xlab=expression(paste(delta^13, "C (\u2030)",sep="")), 
     ylab=expression(paste(delta^15, "N (\u2030)",sep="")),mix_name='Pekan')

simmr_groups_out = simmr_mcmc(simmr_groups)

#Combining sources
simmr_out_combine = combine_sources(simmr_groups_out,
                                    to_combine=c('Bleuet','Sorbier'),
                                    new_source_name='BleuetSorbier')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('BleuetSorbier','Lievre'),
                                    new_source_name='Berries & Hare')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('Campagnol','Souris'),
                                    new_source_name='Small rodents')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('Castor','Porcepic'),
                                    new_source_name='Large rodents')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('cerf','Orignal'),
                                    new_source_name='Cervids')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('Ecureuil','Polatouche'),
                                    new_source_name='Medium rodents')

#Plots for all consumers work fine
plot(simmr_out_combine$input)

plot(simmr_out_combine,type='boxplot',title='simmr output: combined sources')

#Plots for each groups show the general plot for all consumers independently of which group I specify
plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 1)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 2)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 3)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 4)

I attached my simmr input data.

**Comment by andrewcparnell** [comment]
Hi Jerome,

Your data didn't come through, but I think this is a bug I fixed the other day and is now in the development version. If you install the GitHub version with:
```
if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr',build_vignettes =TRUE)
```
See if that fixes the issue.

Andrew

**Comment by JeromeL9** [comment]
Thanks a lot.

I will look at it on Monday.

Have a great weekend!

Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]


De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : June-19-20 2:49 PM
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


Hi Jerome,

Your data didn't come through, but I think this is a bug I fixed the other day and is now in the development version. If you install the GitHub version with:

if(!require(remotes)) install.packages('remotes')

remotes::install_github('andrewcparnell/simmr',build_vignettes =TRUE)

See if that fixes the issue.

Andrew

**Comment by JeromeL9** [comment]
I tried it and it did not fix the issue. I attached my data here if it helps.

Thanks again.

Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]


De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : June-19-20 2:49 PM
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


Hi Jerome,

Your data didn't come through, but I think this is a bug I fixed the other day and is now in the development version. If you install the GitHub version with:

if(!require(remotes)) install.packages('remotes')

remotes::install_github('andrewcparnell/simmr',build_vignettes =TRUE)

See if that fixes the issue.

Andrew

**Comment by andrewcparnell** [comment]
I still can't see your files, but here's a version using something very similar to your code but with the Geese data set included in the package. See if that helps.

```
# R script for Jerome Laliberté

if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr')
library(simmr)
packageVersion('simmr') # Should be 0.4.3

data("geese_data")

# Load into simmr
simmr_groups = with(geese_data, 
               simmr_load(mixtures = mixtures,
                          source_names=source_names,
                          source_means=source_means,
                          source_sds=source_sds,
                          correction_means=correction_means,
                          correction_sds=correction_sds,
                          concentration_means = concentration_means,
                          group = groups))

plot(simmr_groups,group=1:4,xlab=expression(paste(delta^13, "C (\u2030)",sep="")),
     ylab=expression(paste(delta^15, "N (\u2030)",sep="")),mix_name='Pekan')

simmr_groups_out = simmr_mcmc(simmr_groups_in)

#Combining sources
simmr_out_combine = combine_sources(simmr_groups_out,
                                    to_combine=c('U.lactuca','Enteromorpha'),
                                    new_source_name='U+E')
simmr_out_combine = combine_sources(simmr_out_combine,
                                    to_combine=c('Grass','U+E'),
                                    new_source_name='U+E+G')

#Plots for all consumers work fine
plot(simmr_out_combine$input)

plot(simmr_out_combine,type='boxplot',title='simmr output: combined sources')

#Plots for each groups show the general plot for all consumers independently of which group I specify
plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 1)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 2)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 3)

plot(simmr_out_combine,
     type = 'boxplot',
     title = 'simmr output: combined sources',
     group = 4)
```

**Comment by JeromeL9** [comment]
Hi Andrew,

I am working on your solution. I noticed that my r version was outdated on my work computer, could it be the reason that I can’t update simmr? I’m stuck on the 0.4.2 version. Even if I run the code you sent me, the package won’t update.

Thanks a lot, again.

Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]

De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : 19 juin 2020 17:10
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


I still can't see your files, but here's a version using something very similar to your code but with the Geese data set included in the package. See if that helps.

# R script for Jerome Laliberté







if(!require(remotes)) install.packages('remotes')



remotes::install_github('andrewcparnell/simmr')



library(simmr)



packageVersion('simmr') # Should be 0.4.3







data("geese_data")







# Load into simmr



simmr_groups = with(geese_data,



               simmr_load(mixtures = mixtures,



                          source_names=source_names,



                          source_means=source_means,



                          source_sds=source_sds,



                          correction_means=correction_means,



                          correction_sds=correction_sds,



                          concentration_means = concentration_means,



                          group = groups))







plot(simmr_groups,group=1:4,xlab=expression(paste(delta^13, "C (\u2030)",sep="")),



     ylab=expression(paste(delta^15, "N (\u2030)",sep="")),mix_name='Pekan')







simmr_groups_out = simmr_mcmc(simmr_groups_in)







#Combining sources



simmr_out_combine = combine_sources(simmr_groups_out,



                                    to_combine=c('U.lactuca','Enteromorpha'),



                                    new_source_name='U+E')



simmr_out_combine = combine_sources(simmr_out_combine,



                                    to_combine=c('Grass','U+E'),



                                    new_source_name='U+E+G')







#Plots for all consumers work fine



plot(simmr_out_combine$input)







plot(simmr_out_combine,type='boxplot',title='simmr output: combined sources')







#Plots for each groups show the general plot for all consumers independently of which group I specify



plot(simmr_out_combine,



     type = 'boxplot',



     title = 'simmr output: combined sources',



     group = 1)







plot(simmr_out_combine,



     type = 'boxplot',



     title = 'simmr output: combined sources',



     group = 2)







plot(simmr_out_combine,



     type = 'boxplot',



     title = 'simmr output: combined sources',



     group = 3)







plot(simmr_out_combine,



     type = 'boxplot',



     title = 'simmr output: combined sources',



     group = 4)

**Comment by andrewcparnell** [comment]
Perhaps try running:
```
remove.packages('simmr')
if(!require(remotes)) install.packages('remotes')
remotes::install_github('andrewcparnell/simmr')
library(simmr)
packageVersion('simmr') # Should be 0.4.3
```

**Comment by JeromeL9** [comment]
I get this error message when I try to install simmr from your GitHub :

WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
√  checking for file 'C:\Users\lalje4\AppData\Local\Temp\Rtmpy64AYG\remotes1f1429734ca\andrewcparnell-simmr-9d351fc/DESCRIPTION' ...
-  preparing 'simmr': (410ms)
√  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'simmr_0.4.3.tar.gz'

'\\se110b\usagers\lalje4'
CMD.EXE a ‚t‚ d‚marr‚ avec le chemin d'accŠs comme r‚pertoire en
cours. Les chemins d'accŠs UNC ne sont pas prise en charge. Utilisation
du r‚pertoire Windows par d‚faut.
* installing *source* package 'simmr' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'ggplot2' was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package 'simmr'
* removing 'C:/Mrnmicro/Applic/R-4.0.0/library/simmr'
Error: Failed to install 'simmr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/lalje4/AppData/Local/Temp/Rtmpy64AYG/file1f14447f28da/simmr_0.4.3.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers


Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]


De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : June-22-20 5:57 PM
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


Perhaps try running:

remove.packages('simmr')

if(!require(remotes)) install.packages('remotes')

remotes::install_github('andrewcparnell/simmr')

library(simmr)

packageVersion('simmr') # Should be 0.4.3

**Comment by andrewcparnell** [comment]
Hmmm. The error seems to be this:
`Error: (converted from warning) package 'ggplot2' was built under R version 4.0.2`
That suggests that you've conflicting versions of R and packages. I would make sure you have R version 4.0.2. I'm not sure why it's converting that warning to an error though.

**Comment by JeromeL9** [comment]
That might be the problem. The latest approved version by our organisation’s IT department is 4.0.0.

Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]


De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : June-23-20 10:02 AM
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


Hmmm. The error seems to be this:
Error: (converted from warning) package 'ggplot2' was built under R version 4.0.2
That suggests that you've conflicting versions of R and packages. I would make sure you have R version 4.0.2. I'm not sure why it's converting that warning to an error though.

**Comment by andrewcparnell** [comment]
Apparently you can avoid this error by running
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)`
See if that helps.

**Comment by JeromeL9** [comment]
It works! Thanks a lot!

Jérôme Laliberté
Biologiste M.Sc.
Direction de la gestion de la faune du Bas-Saint-Laurent
Ministère des Forêts, de la Faune et des Parcs
92, 2e Rue Ouest, bureau 207
Rimouski (Québec) G5L 8B3
Téléphone : 418 727-3710, poste 446
Télécopieur : 418 727-3735
jerome.laliberte@mffp.gouv.qc.ca<mailto:jerome.laliberte@mffp.gouv.qc.ca>
mffp.gouv.qc.ca<http://www.mffp.gouv.qc.ca/accueil.jsp>
[http://www.intranet/signature/images/Signature-courriel-MFFP.jpg]


De : Andrew Parnell [mailto:notifications@github.com]
Envoyé : June-23-20 10:24 AM
À : andrewcparnell/simmr <simmr@noreply.github.com>
Cc : Laliberté, Jérôme (01-DGFa) <Jerome.Laliberte@mffp.gouv.qc.ca>; Author <author@noreply.github.com>
Objet : Re: [andrewcparnell/simmr] Group simmr output boxplot are always the same (#23)


Apparently you can avoid this error by running
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE)
See if that helps.
